spring:
  application:
    name: commerce-user
    
server:
  port: 8302
  
  eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8303/eureka/
  instance:
    hostname: localhost